### ISSUE TITLE
Stack layout tracker

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#1076]
The following changes should occur with stack functionality turned off, unless a build flag is set to enable it:

- [ ] Add `Stack` to `ILayoutEngine`, which contains a list of windows
  - [ ] Each stack should contain just a single window
  - [ ] Dropping a window into a stack should replace the window in the stack
- [ ] Adding/removing windows from a stack, via commands:
  - [ ] Move window to stack in direction
  - [ ] Unstack window
- [ ] Follow-up commands:
  - [ ] Focus next window in stack
- [ ] Focus previous window in stack
- [ ] Focus adjacent stack in direction
- [ ] Drag-and-drop to stack
  - [ ] Holding down a modifier key to stack
  - [ ] Holding down a modifier key to move not stacked
  - [ ] Dragging a window to the center of the stack

Once the core functionality is implemented, the stack functionality can be enabled by default, and the plugins can be updated to use it:

- [ ] LayoutPreview
- [ ] Bar
