### ISSUE TITLE
Consider moving `DoLayout` to `WorkspaceManager` or `ButlerChores`

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#789]
## Rationale

- It would make `Workspace` simply a container for `ILayoutEngine`s and `IWindow`s. 
- It would make it possible to update `Workspace`s without updating their layout.

## Options

1. ~~Move `DoLayout` to `WorkspaceManager`~~
2. ~~Move `DoLayout` to `ButlerChores`~~
3. Keep `DoLayout` in `Workspace`, but don't call `DoLayout` within `Workspace`.

## TODOs

- [x] Remove `DoLayout` calls from within `Workspace`
- [x] Consider how to notify interested parties that a layout engine has been replaced
- [x] Add `DoLayout` calls where necessary
- [x] Test
- [x] Remove obsolete `IWorkspace` methods
- [x] Improve debugging for handle
- [x] Moving a minimized window to another workspace breaks things in a single monitor
- [x] Moving a visible window to another an adjacent monitor breaks in a multi-monitor setup
- [x] Move `TreeLayoutEngine` fix into a separate branch
- [x] Coverage

## Methods which formerly contained `DoLayout`

- [x] `AddWindow`
- [x] `RemoveWindow`
- [x] `FocusWindowInDirection`
- [x] `SwapWindowInDirection`
- [x] `MoveWindowEdgesInDirection`
- [x] `MinimizeWindowStart`
- [x] `MinimizeWindowEnd`
- [x] `TrySetLayoutEngineFromIndex`
- [x] `PerformCustomLayoutEngineAction`

## Minimized window repro

1. Start Whim
2. Minimize all windows
3. Focus Spotify
4. Minimize Spotify
5. Move Spotify to another workspace
6. Activate the original workspace
