### ISSUE TITLE
Don't move windows when removing/adding monitors

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#817]
When Windows removes a monitor, it will move windows. Based on that, Whim receives window added and window moved events.

## Reproduction

Test by removing dock cable then plugging it in before Windows has a chance to reconcile.

## Requirements

- [x] Windows do not all appear on the single monitor after repro steps
- [x] Layout is retained when restoring monitors

## Proposed fix

- Ignore events until after a timer triggered by a monitor change event
- The timer will be reset by subsequent monitor change events
- After the timer completes, do a complete layout

## TODOs

- [x] Allow events for windows which aren't tracked
- [x] Manual tests
- [x] Tests
- [x] TODOs
- [x] Docs
